### ISSUE TITLE
do not pass structures

### ISSUE THREAD

**Issue by andreikeis** [bretttegart/treadmill_createserver#10]
https://github.com/bretttegart/treadmill_createserver/blob/74b0bc50196a71a758763cd4c455c811d33d947b/lib/python/treadmill/aws/manager.py#L18

seems like manifest is a structure (and name manifest implies that it is some sort of string in yaml/json format - which is it not).

pass arguments directly - in this case it is count. this is low level API, make it as explicit as possible.

**Comment by bretttegart** [comment]
OK, manifest replaced by named arguments.
