### ISSUE TITLE
do not import from os

### ISSUE THREAD

**Issue by andreikeis** [bretttegart/treadmill_createserver#11]
https://github.com/bretttegart/treadmill_createserver/blob/74b0bc50196a71a758763cd4c455c811d33d947b/lib/python/treadmill/aws/server/services.py#L1

out standard is to import module.

correct:

import os
os.environ.get()

incorrect:

from os import environ
environ.get(...)

thoughtworks did not follow the practice, something we need to change. new code should follow this standard.

**Comment by bretttegart** [comment]
Ok, imports fixed!
