### ISSUE TITLE
subnet is not cell

### ISSUE THREAD

**Issue by andreikeis** [bretttegart/treadmill_createserver#13]
https://github.com/bretttegart/treadmill_createserver/blob/74b0bc50196a71a758763cd4c455c811d33d947b/lib/python/treadmill/cli/admin/aws.py#L36

somehow subnet and cell became same, they are not. subnet can have multiple cells.

if you want it as env variable - TREADMILL_AWS_SUBNET (TREADMILL_EC2_SUBNET?) - need prefix for all AWS environment vars to be consistent, but this is NOT cell.

**Comment by bretttegart** [comment]
OK, CLI made more explicit.
