### ISSUE TITLE
domain is already handled

### ISSUE THREAD

**Issue by andreikeis** [bretttegart/treadmill_createserver#14]
https://github.com/bretttegart/treadmill_createserver/blob/74b0bc50196a71a758763cd4c455c811d33d947b/lib/python/treadmill/cli/admin/aws.py#L26

if you need treadmill dns domain, proper way of accessing it:

from treadmill import context

...
context.GLOBAL.dns_domain

no need to add cli option, it is handled and processed at the core CLI context.

**Comment by bretttegart** [comment]
Switched to using Treadmill dns_domain.
