### ISSUE TITLE
cant have ms-aws-ms-com

### ISSUE THREAD

**Issue by andreikeis** [bretttegart/treadmill_createserver#18]
https://github.com/bretttegart/treadmill_createserver/blob/74b0bc50196a71a758763cd4c455c811d33d947b/lib/python/treadmill/aws/server/services.py#L171

can't hardcode ms-aws or anything along these lines. not only it is not appropriate for OS, but all hardcoded/defaults should come from top level CLI.

if this is argument - make it CLI option with env variable TREADMILL_<something>

**Comment by bretttegart** [comment]
OK, value now passed to function instead of being hardcoded.
