### ISSUE TITLE
names of the API must be CRUD

### ISSUE THREAD

**Issue by andreikeis** [bretttegart/treadmill_createserver#23]
https://github.com/bretttegart/treadmill_createserver/blob/9c8d4f163b0f300dba845e386f5dcab4ea14f043/lib/python/treadmill_aws/api/host.py#L32

the names:

self.list_servers = ...

must be:

self.list
self.create
self.delete
seld.update

this may not matter now, but the moment we introduce authorization plugin, it will matter, cause our security policies expect standard verbs.

**Comment by bretttegart** [comment]
OK, fixed!
