### ISSUE TITLE
no need to add every module to entry points

### ISSUE THREAD

**Issue by andreikeis** [bretttegart/treadmill_createserver#24]
https://github.com/bretttegart/treadmill_createserver/blob/9c8d4f163b0f300dba845e386f5dcab4ea14f043/lib/python/Treadmill_AWS.egg-info/entry_points.txt#L16

entry points is something treadmill runtime understands, no need to add treadmill.manager - nobody understand that and not loading this dynamically.

nit - at some point we will need to remove cloud/infra what not and have one group. probably separate PR refactoring CLI so that it is nice.

**Comment by bretttegart** [comment]
Ok, removed from file!
