### ISSUE TITLE
functions that do not use "self" - no need to be part of the class.

### ISSUE THREAD

**Issue by andreikeis** [bretttegart/treadmill_createserver#9]
https://github.com/bretttegart/treadmill_createserver/blob/74b0bc50196a71a758763cd4c455c811d33d947b/lib/python/treadmill/aws/manager.py#L11

generally speaking i prefer functions over classes. they are easier to reason about.

if you need to pass ipaclient, aws client as arguments, make it function argument.

**Comment by bretttegart** [comment]
OK, functions moved outside class structures.
